version: 2
updates:
# v0.1 branch configuration
  - package-ecosystem: gomod
    directory: /
    target-branch: "v0.1"
    schedule:
      interval: daily
    commit-message:
      prefix: "[v0.1] vendor:"
    open-pull-requests-limit: 3
    rebase-strategy: "disabled"
    groups:
      k8s-deps:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: "v0.1"
    schedule:
      interval: daily
    commit-message:
      prefix: "[v0.1] ci:"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"

  - package-ecosystem: docker
    directory: /
    target-branch: "v0.1"
    schedule:
      interval: daily
    commit-message:
      prefix: "[v0.1] docker:"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"

# main branch configuration
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "vendor:"
    open-pull-requests-limit: 3
    rebase-strategy: "disabled"
    groups:
      k8s-deps:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "ci:"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "docker:"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
