# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/main/.golangci.yaml as a
# reference.
run:
  timeout: 5m  # default is 1m
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - gocheckcompilerdirectives
    - gocritic
    - gofmt
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - noctx
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tenv
    - testifylint
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
linters-settings:
  gocritic:
    disabled-checks:
      - exitAfterDefer
      - singleCaseSwitch
  goheader:
    template-path: ./HEADER
  gosec:
    # available rules: https://github.com/securego/gosec#available-rules
    includes: [] # include all available rules
    excludes:
      - G104 # Audit errors not checked
      - G307 # Deferring a method which returns an error
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  importas:
    no-unaliased: true
    alias:
      - pkg: github.com/cilium/cilium/api/v1/flow
        alias: flowpb
      - pkg: github.com/cilium/cilium/api/v1/observer
        alias: observerpb
      - pkg: github.com/cilium/cilium/api/v1/relay
        alias: relaypb
      - pkg: github.com/cilium/fake/flow
        alias: fakeflow
  perfsprint:
    strconcat: false
  revive:
    rules:
      - name: package-comments
        disabled: true
  sloglint:
    static-msg: true
issues:
  # Default rules exclude Go doc comments check, which is rather unfortunate.
  # In order to enable Go doc checks, defaults rules have to be disabled.
  # See https://github.com/golangci/golangci-lint/issues/456 for details.
  exclude-use-default: false
  exclude:
    - Potential file inclusion via variable # EXC0010 gosec: False positive is triggered by 'src, err := io.ReadFile(filename)'

  exclude-rules:
    - linters: [err113]
      text: "do not define dynamic errors, use wrapped static errors instead"
