# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/main/.golangci.yaml as a
# reference.
version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - exptostd
    - gocheckcompilerdirectives
    - gocritic
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - noctx
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    gocritic:
      disabled-checks:
        - exitAfterDefer
        - singleCaseSwitch
    goheader:
      template-path: ./HEADER
    gosec:
      excludes:
        - G104 # Audit errors not checked
        - G307 # Deferring a method which returns an error
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    importas:
      no-unaliased: true
      alias:
        - pkg: github.com/cilium/cilium/api/v1/flow
          alias: flowpb
        - pkg: github.com/cilium/cilium/api/v1/observer
          alias: observerpb
        - pkg: github.com/cilium/cilium/api/v1/relay
          alias: relaypb
        - pkg: github.com/cilium/fake/flow
          alias: fakeflow
    perfsprint:
      strconcat: false
    revive:
      rules:
        - name: package-comments
          disabled: true
    sloglint:
      static-msg: true
  exclusions:
    rules:
      - linters:
          - err113
        text: "do not define dynamic errors, use wrapped static errors instead"
      - path: (.+)\.go$
        text: Potential file inclusion via variable # EXC0010 gosec: False positive is triggered by 'src, err := io.ReadFile(filename)'
formatters:
  enable:
    - gofmt
    - goimports
