# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/main/.golangci.yaml as a
# reference.
version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godoclint
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - ireturn
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - sloglint
    - staticcheck
    - tagalign
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    gocritic:
      disabled-checks:
        - exitAfterDefer
        - singleCaseSwitch
    godoclint:
      default: all
      disable:
        - require-pkg-doc
      options:
        require-doc:
          # Ignore unexported (private) symbols when applying the `require-doc` rule.
          ignore-unexported: true
    goheader:
      template-path: ./HEADER
    gomodguard:
      blocked:
        modules:
          - github.com/goccy/go-yaml:
              recommendations:
                - go.yaml.in/yaml/v3
              reason: "Let's consolidate on a single YAML library that is also used by most of our dependencies"
          - gopkg.in/yaml.v2:
              recommendations:
                - go.yaml.in/yaml/v3
              reason: "gopkg.in/yaml.v2 is unmaintained"
          - gopkg.in/yaml.v3:
              recommendations:
                - go.yaml.in/yaml/v3
              reason: "gopkg.in/yaml.v3 is unmaintained"
          - go.uber.org/multierr:
              recommendations:
                - errors
              reason: "Go 1.20+ has support for combining multiple errors, see https://go.dev/doc/go1.20#errors"
          - go.yaml.in/yaml/v2:
              recommendations:
                - go.yaml.in/yaml/v3
              reason: "We are using v3"
    gosec:
      # available rules: https://github.com/securego/gosec#available-rules
      includes: [] # include all available rules
      excludes:
        - G104 # Audit errors not checked
        - G307 # Deferring a method which returns an error
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    importas:
      no-unaliased: true
      alias:
        - pkg: github.com/cilium/cilium/api/v1/flow
          alias: flowpb
        - pkg: github.com/cilium/cilium/api/v1/observer
          alias: observerpb
        - pkg: github.com/cilium/cilium/api/v1/relay
          alias: relaypb
        - pkg: github.com/cilium/fake/flow
          alias: fakeflow
    perfsprint:
      strconcat: false
    revive:
      rules:
        - name: package-comments
          disabled: true
    sloglint:
      no-mixed-args: true
      no-global: all
      static-msg: true
      key-naming-case: kebab # be consistent with key names
      forbidden-keys: # let's no use reserved log keys
        - level
        - msg
        - source
        - time
  exclusions:
    rules:
      - linters:
          - err113
        text: "do not define dynamic errors, use wrapped static errors instead"
      - path: (.+)\.go$
        text: Potential file inclusion via variable # EXC0010 gosec: False positive is triggered by 'src, err := io.ReadFile(filename)'
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/cilium/certgen/
issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable (default is 50)
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable (default is 3)
  max-same-issues: 0
