name: Go build
on:
  pull_request: {}
  push:
    branches:
      - main
      - v0.1
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        with:
          go-version-file: 'go.mod'
      - name: Formatting check
        run: |
          go fmt ./...
          git diff --exit-code
      - name: Go mod check
        run: |
          go mod tidy
          go mod vendor
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)
      - name: Run static checks
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86
        with:
          version: v1.59.1
          # use our .golangci.yml and configure output to be logged in the GHA, in addition to annotating the commit.
          # see https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648 for output
          args: --config=.golangci.yml --verbose --out-${NO_FUTURE}format colored-line-number
          skip-cache: true
      - name: govulncheck
        uses: golang/govulncheck-action@dd0578b371c987f96d1185abb54344b44352bd58
        with:
          go-version-file: 'go.mod'
          go-package: './...'
      - name: Build
        run: |
          go build ./...
      - name: Test
        run: |
          go test ./...
