name: Go build
on:
  pull_request: {}
  push:
    branches:
      - master
      - v0.1
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version-file: 'go.mod'
      - name: Formatting check
        run: |
          go fmt ./...
          git diff --exit-code
      - name: Go mod check
        run: |
          go mod tidy
          go mod vendor
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)
      - name: Run static checks
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84
        with:
          version: v2.0.1
          # use our .golangci.yml
          args: --config=.golangci.yml --verbose
          skip-cache: true
      - name: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee
        with:
          go-version-file: 'go.mod'
          go-package: './...'
      - name: Build
        run: |
          go build ./...
      - name: Test
        run: |
          go test ./...
