name: Go build
on:
  pull_request: {}
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.1
      - name: Checkout code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Formatting check
        run: |
          go fmt ./...
          git diff --exit-code
      - name: Go mod check
        run: |
          go mod tidy
          go mod vendor
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)
      - name: Run static checks
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.43.0
          args: --config=.golangci.yml --verbose
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Build
        run: |
          go build ./...
      - name: Test
        run: |
          go test ./...
