name: Go build
on:
  pull_request: {}
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: '1.20.2'
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Formatting check
        run: |
          go fmt ./...
          git diff --exit-code
      - name: Go mod check
        run: |
          go mod tidy
          go mod vendor
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)
      - name: Run static checks
        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299
        with:
          version: v1.52.2
          # use our .golangci.yml and configure output to be logged in the GHA, in addition to annotating the commit.
          # see https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648 for output
          args: --config=.golangci.yml --verbose --out-${NO_FUTURE}format colored-line-number
          skip-cache: true
      - name: Build
        run: |
          go build ./...
      - name: Test
        run: |
          go test ./...
