name: Go build
on:
  pull_request: {}
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.6
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: src/github.com/cilium/certgen
      - name: Lint
        working-directory: src/github.com/cilium/certgen
        run: |
          go fmt ./...
          go vet ./...
          git diff --exit-code
      - name: Go mod check
        working-directory: src/github.com/cilium/certgen
        run: |
          go mod tidy
          go mod vendor
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)
      - name: Build
        working-directory: src/github.com/cilium/certgen
        run: |
          go build ./...
      - name: Test
        working-directory: src/github.com/cilium/certgen
        run: |
          go test ./...
