name: Go build
on:
  pull_request: {}
  push:
    branches:
      - master
      - v0.1
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Install Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: 'go.mod'
      - name: Formatting check
        run: |
          go fmt ./...
          git diff --exit-code
      - name: Go mod check
        run: |
          go mod tidy
          go mod vendor
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)
      - name: Run static checks
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64
        with:
          version: v1.59.1
          # use our .golangci.yml and configure output to be logged in the GHA, in addition to annotating the commit.
          # see https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648 for output
          args: --config=.golangci.yml --verbose --out-${NO_FUTURE}format colored-line-number
          skip-cache: true
      - name: govulncheck
        uses: golang/govulncheck-action@dd0578b371c987f96d1185abb54344b44352bd58
        with:
          go-version-file: 'go.mod'
          go-package: './...'
      - name: Build
        run: |
          go build ./...
      - name: Test
        run: |
          go test ./...
